core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("companies/", views.CompanyListView.as_view(), name="company-list"),
    path("companies/new/", views.CompanyCreateView.as_view(), name="company-create"),
    path(
        "companies/edit/<int:pk>/",
        views.CompanyCreateView.as_view(),
        name="company-edit",
    ),
    path(
        "companies/detail/<int:pk>/",
        views.CompanyDetailView.as_view(),
        name="company-detail",
    ),
    path(
        "companies/update/<int:pk>/",
        views.CompanyUpdateView.as_view(),
        name="company-update",
    ),
    path(
        "companies/delete/<int:pk>/",
        views.CompanyDeleteView.as_view(),
        name="company-delete",
    ),
    path("projects/", views.ProjectListView.as_view(), name="project-list"),
    path(
        "projects/suggest_name/",
        views.ProjectSuggestNameView.as_view(),
        name="project-suggest-name",
    ),
    path("projects/new/", views.ProjectCreateView.as_view(), name="project-create"),
    path(
        "projects/detail/<int:pk>/",
        views.ProjectDetailView.as_view(),
        name="project-detail",
    ),
    path(
        "projects/update/<int:pk>/",
        views.ProjectUpdateView.as_view(),
        name="project-update",
    ),
    path(
        "projects/delete/<int:pk>/",
        views.ProjectDeleteView.as_view(),
        name="project-delete",
    ),
    path("tasks/", views.TaskListView.as_view(), name="task-list"),
    path("tasks/clear/", views.ClearTasksView.as_view(), name="task-clear"),
    path("tasks/new/", views.TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/detail/<int:pk>/",
        views.TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "tasks/update/<int:pk>/",
        views.TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/done/<int:pk>/",
        views.TaskDoneView.as_view(),
        name="task-done",
    ),
    path("tf/", views.TableFilterListView.as_view(), name="table-filter-list"),
]

unpoly_demo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html")),
    path("admin/", admin.site.urls),
    path('core/', include('core.urls'))
]

core/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator


class Company(models.Model):
    name = models.CharField(max_length=128, unique=True)
    address = models.TextField()

    def get_absolute_url(self):
        return reverse("company-detail", kwargs={"pk": self.pk})
    
    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=128, unique=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    budget = models.DecimalField(
        max_digits=10, decimal_places=2, validators=[MinValueValidator(100)]
    )

    def get_absolute_url(self):
        return reverse("project-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name
    

class Task(models.Model):
    text = models.TextField()
    done = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("task-detail", kwargs={"pk": self.pk})

core/views.py
from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
    DetailView,
    TemplateView,
    DeleteView,
    View,
)
from django.views.generic.detail import SingleObjectMixin
from django.urls import reverse
from . import models, tables, filters
from django import forms
from django.http import HttpResponseRedirect
from django_tables2 import RequestConfig
from django.contrib import messages
from django.forms import models as model_forms
from django.forms import Textarea


class FormMixin:
    def form_valid(self, form):
        if form.is_valid() and not self.request.up.validate:
            if hasattr(self, "success_message"):
                messages.success(self.request, self.success_message)
            return super().form_valid(form)
        return self.render_to_response(self.get_context_data(form=form))

    def get_initial(self):
        initial = super().get_initial()

        initial.update(self.request.GET.dict())
        return initial


class SmallAddressMixin:
    def get_form_class(self):
        return model_forms.modelform_factory(
            self.model,
            fields=self.fields,
            widgets={
                "address": Textarea(
                    attrs={
                        "rows": 4,
                        "cols": 20,
                    }
                )
            },
        )


class CompanyListView(ListView):
    model = models.Company


class CompanyDetailView(DetailView):
    model = models.Company


class CompanyCreateView(SmallAddressMixin, FormMixin, CreateView):
    success_message = "Company created successfully"
    model = models.Company
    fields = ["name", "address"]


class CompanyUpdateView(SmallAddressMixin, FormMixin, UpdateView):
    model = models.Company
    success_message = "Company updated successfully"
    fields = ["name", "address"]


class CompanyDeleteView(DeleteView):
    model = models.Company

    def get_success_url(self):
        return reverse("company-list")

    def form_valid(self, form):
        self.request.up.layer.emit("company:destroyed", {})
        messages.success(self.request, "Company deleted successfully")
        return super().form_valid(form)


class ProjectDetailView(DetailView):
    model = models.Project


class ProjectDeleteView(DeleteView):
    model = models.Project

    def get_success_url(self):
        return reverse("project-list")

    def form_valid(self, form):
        self.request.up.layer.emit("project:destroyed", {})
        messages.success(self.request, "Project deleted successfully")
        return super().form_valid(form)


class ProjectCreateView(FormMixin, CreateView):
    model = models.Project
    success_message = "Project created successfully"
    fields = ["name", "budget", "company"]


class ProjectUpdateView(FormMixin, UpdateView):
    model = models.Project
    success_message = "Project updated successfully"
    fields = ["name", "budget", "company"]


class ProjectListView(ListView):
    model = models.Project


class ProjectSuggestNameView(TemplateView):
    template_name = "core/project_suggest_name.html"

    def get_context_data(self, **kwargs):
        import random

        ctx = super().get_context_data(**kwargs)
        names = []
        random.shuffle(ANIMALS)
        for i in range(10):
            names.append("-".join(ANIMALS[i * 3 : (i + 1) * 3]))
        ctx["names"] = names

        return ctx


class TaskListView(ListView):
    model = models.Task

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["tasks"] = models.Task.objects.all().order_by("-id")
        return ctx


class TaskForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={"rows": 2, "cols": 40}))

    class Meta:
        model = models.Task
        fields = ["text"]


class TaskCreateView(FormMixin, CreateView):
    model = models.Task
    form_class = TaskForm
    success_message = "Task created successfully"


class TaskDetailView(DetailView):
    model = models.Task


class TaskUpdateView(FormMixin, UpdateView):
    model = models.Task
    form_class = TaskForm
    success_message = "Task updated successfully"


class TaskDoneView(SingleObjectMixin, View):
    model = models.Task

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.done = not self.object.done
        self.object.save()
        messages.success(self.request, "Task marked as done!")
        return HttpResponseRedirect(self.object.get_absolute_url())


class ClearTasksView(View):
    def post(self, request, *args, **kwargs):
        models.Task.objects.filter(done=True).delete()
        messages.success(self.request, "Tasks cleared!")
        return HttpResponseRedirect(reverse("task-list"))


class TableFilterListView(ListView):
    model = models.Company
    template_name = "core/company_table_filter.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        filter = filters.CompanyFilter(self.request.GET, self.get_queryset())
        table = tables.CompanyTable(filter.qs)
        RequestConfig(self.request).configure(table)
        ctx["table"] = table
        ctx["filter"] = filter
        return ctx


ANIMALS = [
    "aardvark",
    "aardwolf",
    "albatross",
    "alligator",
    "alpaca",
    "amphibian",
    "anaconda",
    "angelfish",
    "anglerfish",
    "ant",
    "anteater",
    "antelope",
    "antlion",
    "ape",
    "aphid",
    "armadillo",
    "asp",
    "baboon",
    "badger",
    "bandicoot",
    "barnacle",
    "barracuda",
    "basilisk",
    "bass",
    "bat",
    "bear",
    "beaver",
    "bedbug",
    "bee",
    "beetle",
    "bird",
    "bison",
    "blackbird",
    "boa",
    "boar",
    "bobcat",
    "bobolink",
    "bonobo",
    "booby",
    "bovid",
    "bug",
    "butterfly",
    "buzzard",
    "camel",
    "canid",
    "canidae",
    "capybara",
    "cardinal",
    "caribou",
    "carp",
    "cat",
    "caterpillar",
    "catfish",
    "catshark",
    "cattle",
    "centipede",
    "cephalopod",
    "chameleon",
    "cheetah",
    "chickadee",
    "chicken",
    "chimpanzee",
    "chinchilla",
    "chipmunk",
    "cicada",
    "clam",
    "clownfish",
    "cobra",
    "cockroach",
    "cod",
    "condor",
    "constrictor",
    "coral",
    "cougar",
    "cow",
    "coyote",
    "crab",
    "crane",
    "crawdad",
    "crayfish",
    "cricket",
    "crocodile",
    "crow",
    "cuckoo",
    "damselfly",
    "deer",
    "dingo",
    "dinosaur",
    "dog",
    "dolphin",
    "dormouse",
    "dove",
    "dragon",
    "dragonfly",
    "duck",
    "eagle",
    "earthworm",
    "earwig",
    "echidna",
    "eel",
    "egret",
    "elephant",
    "elk",
    "emu",
    "ermine",
    "falcon",
    "felidae",
    "ferret",
    "finch",
    "firefly",
    "fish",
    "flamingo",
    "flea",
    "fly",
    "flyingfish",
    "fowl",
    "fox",
    "frog",
    "galliform",
    "gamefowl",
    "gayal",
    "gazelle",
    "gecko",
    "gerbil",
    "gibbon",
    "giraffe",
    "goat",
    "goldfish",
    "goose",
    "gopher",
    "gorilla",
    "grasshopper",
    "grouse",
    "guan",
    "guanaco",
    "guineafowl",
    "gull",
    "guppy",
    "haddock",
    "halibut",
    "hamster",
    "hare",
    "harrier",
    "hawk",
    "hedgehog",
    "heron",
    "herring",
    "hippopotamus",
    "hookworm",
    "hornet",
    "horse",
    "hoverfly",
    "hummingbird",
    "hyena",
    "iguana",
    "impala",
    "jackal",
    "jaguar",
    "jay",
    "jellyfish",
    "junglefowl",
    "kangaroo",
    "kingfisher",
    "kite",
    "kiwi",
    "koala",
    "koi",
    "krill",
    "ladybug",
    "lamprey",
    "landfowl",
    "lark",
    "leech",
    "lemming",
    "lemur",
    "leopard",
    "leopon",
    "limpet",
    "lion",
    "lizard",
    "llama",
    "lobster",
    "locust",
    "loon",
    "louse",
    "lungfish",
    "lynx",
    "macaw",
    "mackerel",
    "magpie",
    "mammal",
    "manatee",
    "mandrill",
    "marlin",
    "marmoset",
    "marmot",
    "marsupial",
    "marten",
    "mastodon",
    "meadowlark",
    "meerkat",
    "mink",
    "minnow",
    "mite",
    "mockingbird",
    "mole",
    "mollusk",
    "mongoose",
    "moose",
    "mosquito",
    "moth",
    "mouse",
    "mule",
    "muskox",
    "narwhal",
    "newt",
    "nightingale",
    "ocelot",
    "octopus",
    "opossum",
    "orangutan",
    "orca",
    "ostrich",
    "otter",
    "owl",
    "ox",
    "panda",
    "panther",
    "parakeet",
    "parrot",
    "parrotfish",
    "partridge",
    "peacock",
    "peafowl",
    "pelican",
    "penguin",
    "perch",
    "pheasant",
    "pigeon",
    "pike",
    "pinniped",
    "piranha",
    "planarian",
    "platypus",
    "pony",
    "porcupine",
    "porpoise",
    "possum",
    "prawn",
    "primate",
    "ptarmigan",
    "puffin",
    "puma",
    "python",
    "quail",
    "quelea",
    "quokka",
    "rabbit",
    "raccoon",
    "rat",
    "rattlesnake",
    "raven",
    "reindeer",
    "reptile",
    "rhinoceros",
    "roadrunner",
    "rodent",
    "rook",
    "rooster",
    "roundworm",
    "sailfish",
    "salamander",
    "salmon",
    "sawfish",
    "scallop",
    "scorpion",
    "seahorse",
    "shark",
    "sheep",
    "shrew",
    "shrimp",
    "silkworm",
    "silverfish",
    "skink",
    "skunk",
    "sloth",
    "slug",
    "smelt",
    "snail",
    "snake",
    "snipe",
    "sole",
    "sparrow",
    "spider",
    "spoonbill",
    "squid",
    "squirrel",
    "starfish",
    "stingray",
    "stoat",
    "stork",
    "sturgeon",
    "swallow",
    "swan",
    "swift",
    "swordfish",
    "swordtail",
    "tahr",
    "takin",
    "tapir",
    "tarantula",
    "tarsier",
    "termite",
    "tern",
    "thrush",
    "tick",
    "tiger",
    "tiglon",
    "toad",
    "tortoise",
    "toucan",
    "trout",
    "tuna",
    "turkey",
    "turtle",
    "tyrannosaurus",
    "unicorn",

core/templates/core/_task_partial.html
{% load core_tags %}
<div class="card task {% if task.done %}done{% endif %}" tabindex="0">
  <div class="card-body d-flex flex-column">
    <div class="card-text flex-grow-1">
      <b>{{ task.text }}</b>
    </div>
    <div class="flex-grow-0">
      <a up-target='.task' href='{% url "task-update" task.id %}' class='btn btn-sm btn-outline-secondary'  >Edit</a>
      <form method="POST"  up-target='.task' action="{% url 'task-done' task.id %}" class="d-inline">
        {% csrf_token %}
        <button type="submit" class="btn btn-sm btn-outline-info">Done</button>
      </form>
      {% if forloop.counter0 == 0 %}
        {% tourdot %}
          <p>
            This screen shows many task boxes with the same selector
            (<code>&lt;div class="task"&gt;</code>).
          </p>
          <p>
            Note how changing a task will only update a single task box.
          </p>
        {% endtourdot %}
      {% endif %}
    </div>
  </div>
</div>

core/templates/core/company_detail.html
{% extends "base.html" %}
{% load core_tags crispy_forms_tags %}

{% block content %}
  <div class="row mb-4">
    <div class="col">
      <h2>Company {{ company.id }}</h2>
    </div>

    <div class="col-sm-auto">
      {% tourdot %}
        <p>Note how the <i>Edit</i> link renders within this overlay.</p>
        <p>Links and forms always update their own layer unless another layer is targeted explicitly.</p>
      {% endtourdot %}
      
      <a up-follow href='{% url "company-update" company.id %}' class="btn btn-primary" >Edit</a>

      <a class='btn btn-danger' up-layer="new" up-content='
      <h3>Delete company {{ company.name }}</h3>
      Do you want to delete the company? 
      <form up-submit up-layer="root" class="d-inline" method="POST" action="{% url "company-delete" company.id %}">
        {% csrf_token %}
        <input type="submit" value="Yes" class="btn btn-danger mr-3"/>
        <a href="#" class="btn btn-secondary"  up-dismiss>No</a>
      </form>
      '>Delete</a>

    </div>
  </div>

  <dl>
    <dt>Name</dt>
    <dd>{{ company.name }}</dd>
    <dt>Address</dt>
    <dd>
      {{ company.address|linebreaks }}
    </dd>
  </dl>

  <div class="row mb-2">
    <div class="col">
      <h4>Projects</h4>
    </div>

    <div class="col-sm-auto">
      <div class="col-sm-auto">
        {% tourdot %}
          When a new project was created, the project list is
          reloaded automatically.
        {% endtourdot %}
        <a class='btn btn-primary btn-sm'
           href='{% url "project-create" %}?company={{ company.id }}'
           up-layer='new'
           up-accept-location='/core/projects/detail/$id/'
           up-on-accepted='up.reload(".projects")'
           up-context='{"from_company": true}'
        >
          Add project
        </a>

      </div>
    </div>
  </div>

  <div class="projects">
    {% if company.project_set.all %}
      <table class="table table-sm">
        <thead>
          <th>Name</th>
          <th>Budget</th>
        </thead>
        <tbody>
          {% for project in company.project_set.all %}
            <tr>
              <td>
                <a href='{% url "project-detail" project.id %}'
                   up-layer='new'
                   up-dismiss-event='project:destroyed'
                   up-on-dismissed='up.reload(".projects")'
                   up-context='{"from_company": true}'
                >
                  {{ project.name }}
                </a>
                {% if forloop.counter0 == 0 %}
                  {% tourdot %}
                    <p>Opening the project will open another modal over this one.</p>
                    <p>Overlays can be stacked infinitely.</p>
                  {% endtourdot %}
                {% endif %}
              </td>
              <td align="right">
                {{ project.budget }}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>
        This company has no projects yet.
      </p>
    {% endif %}
  </div>


{% endblock %}

core/templates/core/company_form.html
{% extends "base.html" %}
{% load core_tags crispy_forms_tags %}

{% block content %}

    {% if form.instance.id %}
        <h2 class="mb-4">Edit company {{ form.instance }}</h2>
    {% else %}
        <h2 class="mb-4">New company</h2>
    {% endif %}

    <form up-submit up-validate up-disable method="POST">
        {% csrf_token %}
        {% tourdot %}
            <p>The form is being validated on the server as you're completing fields.</p>
            <p>Try entering a duplicate company name and focusing the next field..</p>
        {% endtourdot %}
        {{ form|crispy }}

        <div class="d-flex align-items-center">
            <div class="flex-grow-1">
                <input type='submit' class='btn btn-primary mt-2' value='Save'>
                {% if not for.instance.id %}
                    {% tourdot %}
                        <p>Saving an invalid form will re-render validation errors in the same overlay.</p>
                        <p>Links and forms always render in the same layer unless another layer is targeted explicitly.</p>
                    {% endtourdot %}
                {% endif %}
            </div>

            <div>
                {% if form.instance.id %}
                    <a up-follow class='btn btn-outline-secondary' href='{% url "company-detail" form.instance.id %}'>Cancel</a>
                {% endif %}
            </div>
        </div>
    </form>
{% endblock %}

core/templates/core/company_list.html
{% extends "base.html" %}
{% load core_tags %}

{% block content %}
  <div class="row mb-4">
    <div class="col">
      <h2>All companies</h2>
    </div>

    <div class="col-sm-auto">
      {% tourdot {"overlay": true} %}
        <p>
          The <i>New company</i> button has an <code>[up-layer=new]</code> attribute.
          This causes the link destination to open in an overlay.
        </p>
        <p>
          The button also defines a <i>close condition</i> using an <code>[up-accept-location]</code> attribute.
          This causes the overlay to automatically close when it reaches the URL of a newly created company.
        </p>
        <p>
          The <code>[up-on-accepted]</code> attribute causes the company list below to reload when the overlay closes.
        </p>
      {% endtourdot %}
      
      <a
        class='btn btn-primary'
        up-layer='new'
        up-on-accepted="reloadWithFlash('.table', 'Company created!')"
        up-accept-location='{% urlid "company-detail" "$id" %}'
        href='{% url "company-create" %}'>New company</a>

    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>

    <tbody>
      {% for company in object_list %}
        <tr>
          <td>
            
            <a
              up-layer='new'
              up-on-dismissed="reloadWithFlashIfEvent('.table', 'Company deleted!', value)"
              up-dismiss-event='company:destroyed'
              href="{% url 'company-detail' company.id %}">{{ company.name }}</a>

            {% if forloop.counter0 == 0 %}
              {% tourdot %}
                The link to the company details has an <code>[up-layer=new]</code> attribute.
                This causes the link destination to open in an overlay.
              {% endtourdot %}
            {% endif %}
          </td>
        </tr>
      {% endfor %}

    </tbody>
  </table>

{% endblock %}

core/templates/core/company_table_filter.html
{% extends "base.html" %}
{% load core_tags crispy_forms_tags %}
{% load render_table from django_tables2 %}

{% block content %}
  <div class="row mb-4">
    <div class="col">
      <h2>All companies</h2>
    </div>
  </div>
  <div class="row">
    <div class="col">
        <form up-autosubmit up-history='true' up-watch-delay='250' class='form-inline' method='GET' action='' up-target='.form-data'>
            {{ filter.form|crispy }}
            <input class='btn btn-info' type='submit' value='Filter'>
            <a up-follow href='{{ request.path }}' class='btn btn-secondary'>Reset</a>
        </form>
    </div>
</div>

<div class='row'>
  <div class='col'>
      <div class='form-data'>
        {% render_table table %}
      </div>
    </div>
  </div>

{% endblock %}

core/templates/core/project_detail.html
{% extends "base.html" %}
{% load core_tags crispy_forms_tags %}

{% block content %}
  <div class="row mb-4">
    <div class="col">
      <h2>Project {{ project.id }}</h2>

      {% if up.context.from_company %}
        {% tourdot %}
          <p>
            This overlay reuses the template that is also used for the
            <a up-layer='root' href='{% url "project-list" %}'>Projects</a>
            section
            in the main navigation.
          </p>
        {% endtourdot %}
      {% endif %}
    </div>
    <div class="col-sm-auto">
      {% tourdot %}
        <p>Note how the <i>Edit</i> link renders within this overlay.</p>
        <p>Links and forms always update their own layer unless another layer is targeted explicitly.</p>
      {% endtourdot %}
      
      <a up-follow href='{% url "project-update" project.id %}' class="btn btn-primary">Edit</a>
      <form up-submit up-confirm='Really?' class="d-inline" method='POST' action='{% url "project-delete" project.id %}'>
        {% csrf_token %}
        <input type='submit' value='Delete' class='btn btn-danger mr-3'  />
      </form>

    </div>
  </div>

  <dl>
    <dt>Name</dt>
    <dd>{{ project.name }}</dd>
    <dt>Budget</dt>
    <dd>{{ project.budget }}</dd>
    <dt>Company</dt>
    <dd>{{ project.company }}</dd>

  </dl>



{% endblock %}

core/templates/core/project_form.html
{% extends "base.html" %}
{% load core_tags crispy_forms_tags %}

{% block content %}

    {% if form.instance.id %}
        <h2 class="mb-4">Edit project {{ form.instance }}</h2>
    {% else %}
        <h2 class="mb-4">New project</h2>
    {% endif %}

    <form up-submit up-validate up-disable method="POST">
        {% csrf_token %}
        <div class="input-group-append">
            <span class="input-group-text">
                <a
                    up-layer='new popup'
                    up-align='left'
                    up-size='large'
                    up-accept-event='name:select'
                    up-on-accepted="up.fragment.get('#id_name').value = value.name"
                    href='{% url "project-suggest-name" %}'>Suggest name</a>
                {% tourdot %}
                    <p>
                        The link opens a popup with suggestions for a project name.
                    </p>
                    <p>
                        When a suggestion is clicked, the choice is communicated
                        back to the project form via a custom <code>name:select</code> event.</p>
                    <p>
                        The <i>Suggest name</i> link has an <code>[up-on-accepted]</code>
                        attribute that copies the suggestion into the project form.
                    </p>
                {% endtourdot %}
            </span>
        </div>
        {{ form|crispy }}
        
        <div class="input-group-append">
            <span class="input-group-text">
                <a href='{% url "company-create" %}'
                   up-layer='new'
                   up-accept-location='{% urlid "company-detail" "$id" %}'
                   up-on-accepted="up.validate('form', { params: { 'company': value.id } })"
                >
                    New company
                </a>
                
                {% tourdot %}
                    <p>
                        A new company can be created in an overlay while the incomplete project form
                        stays open in the background.
                    </p>
                    <p>
                        The <i>New company</i> also defines a <i>close condition</i> using an <code>[up-accept-location]</code> attribute.
                        This causes the overlay to automatically close when it reaches the URL of a newly created company.
                    </p>

                    <p>
                        When a company was created successfully, the overlay is automatically closed.
                        The project form reloads the company select box so the new company appears
                        as an option.
                    </p>
                {% endtourdot %}
            </span>
        </div>

        <div class="d-flex align-items-center">
            <div class="flex-grow-1">

                <input type='submit' class='btn btn-primary' value='Save'>

                {% if not form.instance.id %}
                    {% tourdot %}
                        <p>Saving an invalid form will re-render validation errors in the same overlay.</p>
                        <p>Links and forms always render in the same layer unless another layer is targeted explicitly.</p>
                    {% endtourdot %}
                {% endif %}
            </div>

            <div>
                {% if form.instance.id %}
                    <a up-follow class='btn btn-outline-secondary' href='{% url "project-detail" form.instance.id %}'>Cancel</a>
                {% endif %}
            </div>
        </div>

    </form>
{% endblock %}

core/templates/core/project_list.html
{% extends "base.html" %}
{% load core_tags %}

{% block content %}
  <div class="row mb-4">
    <div class="col">
      <h2>All projects</h2>
    </div>

    <div class="col-sm-auto">

      <a
        class='btn btn-primary'
        up-layer='new'
        up-on-accepted="reloadWithFlash('.table', 'Project created!')"
        up-accept-location='/core/projects/detail/$id/'
        href='{% url "project-create" %}'>New project</a>

    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Company</th>
      </tr>
    </thead>

    <tbody>
      {% for project in object_list %}
        <tr>
          <td>
            <a
              up-layer='new'
              up-on-dismissed="reloadWithFlashIfEvent('.table', 'Project deleted!', value)"
              up-dismiss-event='project:destroyed'
              href="{% url 'project-detail' project.id %}">{{ project.name }}</a>

          </td>
          <td>
            {{ project.company.name }}
          </td>
        </tr>
      {% endfor %}

    </tbody>
  </table>

{% endblock %}

core/templates/core/project_suggest_name.html
{% extends "base.html" %}
{% load core_tags %}
{% block content %}
  {% for n in names %}

    {% if forloop.counter0 == 0 %}
      {% tourdot %}
        <p>
          Each suggestion button has an <code>[up-emit="name:select"]</code> attribute.
          When clicked it emits an <code>name:select</code> event on
          the popup element.
        </p>
        <p>
          The link that opened this popup is awaiting this event
          via its <code>[up-accept-event]</code> attribute. When the element
          is observed, the popup is automatically closed and the name copied
          into the project form.
        </p>
      {% endtourdot %}
    {% endif %}

    <a up-emit="name:select"
       up-emit-props='{"name": "{{ n }}"}'
       class="btn btn-info text-light mb-2 mr-1"
       tabindex="0">
      {{ n }}
    </a>

  {% endfor %}
{% endblock %}

core/templates/core/task_detail.html
{% extends "base.html" %}
{% load core_tags crispy_forms_tags %}

{% block content %}
    {% include "core/_task_partial.html" %}
{% endblock %}

core/templates/core/task_form.html
{% extends "base.html" %}
{% load core_tags crispy_forms_tags %}

{% block content %}

    <form up-submit up-disable {% if not up.context.new_task %}up-target='.task'{% endif %} class='task card' method="POST">
        {% csrf_token %}
        <div class="card-body d-flex flex-column">
            <div class="form-group flex-grow-1 mb-0">
                {{ form|crispy }}
            </div>
            <div class="flex-grow-0">
                <input type='submit' class='btn btn-primary mt-2' value='Save'>
            </div>
        </div>
    </form>
{% endblock %}